### ISSUE TITLE
can't install libxml2-utils

### ISSUE THREAD

**Issue by vasudeva-chaynes** [AtomLinter/linter-xmllint#25]
I've installed linter, linter-xmllint, and xmllint successfully, but linter-xmllint doesn't work. xmllint does work from CLI. libxml2-utils install, tried two ways, fails as follows (with Yosemite):

    ~$ sudo apt-get install libxml2-utils
    Password:
    Reading Package Lists... Done
    Building Dependency Tree... Done
    W: Couldn't stat source package list ftp://ftp.logilab.org unstable/ Packages (/sw/var/lib/apt/lists/ftp.logilab.org_pub_debian_unstable_Packages) - stat (2 No such file or directory)
    W: Couldn't stat source package list ftp://ftp.logilab.org unstable/ Packages (/sw/var/lib/apt/lists/ftp.logilab.org_pub_debian_unstable_Packages) - stat (2 No such file or directory)
    W: You may want to run apt-get update to correct these problems
    E: Couldn't find package libxml2-utils
    ~$ brew install --with-python libxml2-utils
    Error: No available formula for libxml2-utils
    ==> Searching formulae...
    ==> Searching taps...
    ~$

**Comment by Arcanemagus** [comment]
This is an issue with your package manager, not `linter-xmllint`. You can try filing an issue on the `xmllint` repository, they might be able to help you there.
