### ISSUE TITLE
not linting on save

### ISSUE THREAD

**Issue by ksnyde** [AtomLinter/linter-xmllint#26]
I put in the executable path and then made an egregious error on my XML and saved it but I could see no linting taking place. Is this plugin actively working at the moment? Is there anything I might be forgetting to do?

OS: `OSX`
Atom: `1.0.19`

**Comment by lucascosti** [comment]
+1 on Fedora 22. Doesn't look like anything is happening.

**Comment by apodacaa** [comment]
yeah nothing is happening

**Comment by Arcanemagus** [comment]
Looks like this linter has been abandoned as it hasn't been updated for the new Linter API (https://github.com/AtomLinter/linter-xmllint/issues/17). Would one of you feel up to re-writing this to support that?

**Comment by dirk-thomas** [comment]
Please take a look at #27. It would be great if others could try the patch and comment if it does (or does not).
