### ISSUE TITLE
How to add the schema for xml validation

### ISSUE THREAD

**Issue by jdouble** [AtomLinter/linter-xmllint#3]
I see that in the development console that it run xmllint.  I do not see how to specify the xsd file that will be used.  I know that when running from the command line I can use the --schema argument to indicate the xsd file.  Am I missing something when running from atom.

**Comment by andya9** [comment]
:+1: 

Implementing this would be a bit tricky, as we cannot hardcode the schema into the package; maybe it could be done by creating a per-project setting file containg the name of the schema, that will be read by the package and replaced as variable... I’ll try, but I don’t know if I am able to do it, as I’m just a newby to programming =)

**Comment by andya9** [comment]
Update: I thought about this a bit more. We may have multiple validators in the same project, and multiple kinds of validators (xml schema, relax, relax compact, dtd, ecc).

So. We have a project with to_be_validated.xml and validator.rng.
1. We create a file called to_be_validated.relax; content: validator.rng
2. in linter-xmllint.coffee there will be this test: 
(for relax ng)
  if to_be_validated.relax exists,  cmd: 'xmllint --noout --relaxng {content of to_be_validated.relax}'
(for wxs schema)
 if to_be_validated.schema exists, cmd: 'xmllint --noout --schema {content of to_be_validated.schema}'
(for schematron)
if to_be_validated.schematron exists, cmd: 'xmllint --noout --schematron {content of to_be_validated.schematron}'
else:
cmd: 'xmllint --noout'

**Comment by adunning** [comment]
It's very exciting to see that you are planning RELAX NG and Schematron support; I do not believe there are any cross-platform, open-source editors that provide live validation for these. Making Atom into a usable environment for working with XML would make a world of difference.

The easiest solution from a user's perspective (implemented e.g. in Oxygen XML) would be to download the schema specified in an xml-model processing instruction, so that for instance a [file beginning with the following lines](http://www.stoa.org/epidoc/gl/latest/supp-structure.html) would be automatically validated:

```xml
<?xml-model href="http://www.stoa.org/epidoc/schema/latest/tei-epidoc.rng"
    schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://www.stoa.org/epidoc/schema/latest/tei-epidoc.rng"
    schematypens="http://purl.oclc.org/dsdl/schematron"?>
```

**Comment by andya9** [comment]
@adunning  Sadly, it seems we can’t do it live, as xmllint can’t check both syntax errors and schema errors in the same time: it will not check if it validates until all spelling errors are fixed.

**Comment by adunning** [comment]
That's not really a problem; I find that one often needs to fix syntax errors in order to get comprehensible errors from the schema in any case.

Oxygen, by the way, uses Jing for RELAX NG, but I assume that it would be better to avoid a dependency on Java. Supposedly lxml can also handle it, but I've never tried this.

**Comment by andya9** [comment]
But if you have live linting enabled, even if you fixed all syntax errors, as soon as you start typing you will have syntax errors until you close tags, preventing the validation check to happen... So we would have validation check only when reviewing.
So maybe it would be better to validate on-demand, not live?

As for lxml, I never tried it too (I’m no professional programmer, just an amateur beginning trying to make the best out of his pc)

**Comment by adunning** [comment]
Anything will be better than validating through the command line.

**Comment by andya9** [comment]
actually the command is really simple: xmllint --noout --relaxng path/to/your/rngschema path/to/your/inputfile. But if you are on windows, yeah, I think it would be a pain...

**Comment by dirk-thomas** [comment]
I have implemented validation against a `.xsd` as well as a `.dtd` file in #28. Please considering try the patched versions and comment on the PR to confirm that it works or doesn't work for you.

Regarding relaxng support: I have never used it and therefore don't know how that schema is referenced within the xml file. If anybody can provide information on that it should be straight forward to integrate.

**Comment by adunning** [comment]
That's wonderful; thank you! Relax NG and Schematron are declared using [`xml-model`](http://www.w3.org/TR/xml-model/); see my example above (can also be used to link a DTD, as shown in linked W3C documentation).

**Comment by andya9** [comment]
I’m trying the updated linter, but nothing happens. Maybe I’m doing it wrong:
\<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/dev/shm/tei_lite.dtd"\>

**Comment by Arcanemagus** [comment]
Since that functionality has been released I'm marking this as closed, please file a new issue if you are still having problems.
