### ISSUE TITLE
Detect schema using xml-model

### ISSUE THREAD

**Issue by adunning** [AtomLinter/linter-xmllint#30]
[xml-model](http://www.w3.org/TR/xml-model/) is a language-independent method of associating a schema with an XML document (essentially a more advanced version of DOCTYPE). Take a look at the Oxygen XML editor if you want an implementation example.

This is the only way for associating Relax NG and Schematron schemata with an XML document, and hence is necessary to implementing #29 (example given there).

**Comment by dirk-thomas** [comment]
I have implemented support to specify XML schemas via `xml-model` in #34. While it still needs some specs it would be great if you could try it out and report back if it works for your use case.

**Comment by adunning** [comment]
That's great; thanks for doing that! Bit hard to test it right now, but that's definitely what I had in mind.

**Comment by dirk-thomas** [comment]
I finally found some time to add specs for the new xml-model processing instructions. I have merge the PR and released 1.2.0.

**Comment by adunning** [comment]
Thank you!

**Comment by andya9** [comment]
Thank’you @dirk-thomas !
