### ISSUE TITLE
Other available linters should be removed from readme

### ISSUE THREAD

**Issue by Andersos** [AtomLinter/linter-xmllint#6]
Since the original linter project lists out the projects it is not needed to list them here.

**Comment by steelbrain** [comment]
:-1: For removing the list of available linters in this repo only. If you want, You can open up a meta bug in the main repo requesting removal of other linters from all repos. Removing from one and keeping in others won't be a good thing to do.

**Comment by Andersos** [comment]
Well the list is incomplete. It's a lot more valuable to link to the full list like @andya9 has suggested.
