### ISSUE TITLE
XSLT doesn't work again

### ISSUE THREAD

**Issue by ketamin** [AtomLinter/linter-xmllint#66]
Hi there,

I didn't check why, but somehow the XSLT support was dropped (which was added in 0.0.7)

Found out, that changing the grammarScopes to following line worked for me

```coffeescript
grammarScopes: ['text.xml','text.xml.xsl']
```

Is it possible, to bring back native XSLT-Support?

**Comment by dirk-thomas** [comment]
It looks indeed like I broke that feature in 4f97338330d1b8c610729cd48fff8b38617b01fd. PR #67 fixes this. I also just released a new version (1.3.6) of the package.
