### ISSUE TITLE
Allow configurable command line options for xmllint

### ISSUE THREAD

**Issue by mrapczynski** [AtomLinter/linter-xmllint#69]
I'm running into a circumstance where the vendor provided schema does not validate by xmllint for a couple various reasons. What I really want `linter-xmllint` to do is provide basic syntax sanity checks, I'm not worried about the schema. I did not see an option anywhere where I could pass a command line flag like `--nonet` to disable those schema checks. Could this be added in the future?

**Comment by dirk-thomas** [comment]
@mrapczynski Please see the PR #70 which adds configuration options to skip the different validation steps individually. I hope that addresses your use case.
