### ISSUE TITLE
error with using on my machine

### ISSUE THREAD

**Issue by 8bitreid** [AtomLinter/linter-xmllint#71]
not sure why this is not running, but I ge
![2016-12-06 15_27_46-testxmlfilestructure xml c__users_rmewborne_desktop_json files atom](https://cloud.githubusercontent.com/assets/9111792/20942262/a69959b8-bbc8-11e6-88bc-59600fc7d4e8.png)
t this error.  thatnks

**Comment by dirk-thomas** [comment]
Do you have the command line programm `xmllint` installed (https://github.com/AtomLinter/linter-xmllint#linter-installation)?

**Comment by 8bitreid** [comment]
the instructions are not very clear.  I'm on a Windows machine. could you provide more specific instructions?

**Comment by 8bitreid** [comment]
to be more specific.. the directory instructions are not very clear in the link provided.  However, I have run amp install linter-xmllint and installed.  I'm just not sure how to follow the instructions in (https://github.com/AtomLinter/linter-xmllint#linter-installation)  thanks!

**Comment by dirk-thomas** [comment]
I am don't have / use a Windows machine myself. Which part of the instructions is not clear / where do you have a problem following them? What are the exact steps you have tried so far?

**Comment by dirk-thomas** [comment]
I will close this for know since the requested information haven't been provided. Please feel free to comment on the closed ticket. If there is enough information I am happy to update the instructions.
