### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Yajo** [AtomLinter/linter-xmllint#74]
I have the addon installed, `xmllint` installed, findable in `$PATH`, and addon enabled.

When I edit a wrong XML file, the linter shows ✔️ No issues.

If I run xmllint manually, it shows:

```
website_event_templates.xml:522: parser error : Opening and ending tag mismatch: div line 493 and template
</template>
           ^
website_event_templates.xml:715: parser error : Opening and ending tag mismatch: template line 482 and odoo
</odoo>
       ^
website_event_templates.xml:716: parser error : Premature end of data in tag odoo line 2
```

**Comment by dirk-thomas** [comment]
Can you please try the current version of the package (1.4.2) and comment if it continues to not work for you. If that is the case please provide more information, e.g. which platform are you on, what `xmllint` version do you have installed, does the linter UI show that `xmllint` was invoked, etc.

**Comment by dirk-thomas** [comment]
I will close this for now due to no response. Please feel free to comment with the additional information and the ticket can be reopened.
