### ISSUE TITLE
Uncaught Error: Unexpected endLine: 0Column: 2Char: 

### ISSUE THREAD

**Issue by creadri** [AtomLinter/linter-xmllint#80]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0-beta0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [linter-xmllint](https://github.com/AtomLinter/linter-xmllint) package 1.4.2

### Stack Trace

Uncaught Error: Unexpected end
Line: 0
Column: 2
Char: 

```
At events.js:160

Error: Unexpected end
Line: 0
Column: 2
Char: 
    at error (/packages/linter-xmllint/node_modules/sax/lib/sax.js:667:10)
    at end (/packages/linter-xmllint/node_modules/sax/lib/sax.js:678:7)
    at Object.end (/packages/linter-xmllint/node_modules/sax/lib/sax.js:154:24)
    at SAXStream.end (/packages/linter-xmllint/node_modules/sax/lib/sax.js:248:18)
    at ReadableString.onend (_stream_readable.js:511:10)
    at ReadableString.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at ReadableString.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -1:46.3.0 application:new-file (div.tool-panel.tree-view)
     -1:40.4.0 core:backspace (input.hidden-input)
     -1:39.1.0 intentions:highlight (input.hidden-input)
     -1:38.9.0 core:save (input.hidden-input)
     -1:32.3.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -1:26.1.0 core:confirm (input.hidden-input)
     -1:21.3.0 intentions:highlight (input.hidden-input)
     -1:21.1.0 autocomplete-plus:activate (input.hidden-input)
  2x -1:10.1.0 core:confirm (input.hidden-input)
  2x -0:08.2.0 core:backspace (input.hidden-input)
     -0:06.8.0 intentions:highlight (input.hidden-input)
     -0:06.6.0 autocomplete-plus:activate (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.8.63 
busy-signal 1.4.1 
intentions 1.1.2 
linter 2.1.4 
linter-markdown 4.0.1 
linter-pycodestyle 2.0.2 
linter-sass-lint 1.7.4 
linter-tidy 2.3.1 
linter-ui-default 1.6.0 
linter-xmllint 1.4.2 
markdown-preview-plus 2.4.9 
tree-view-git-status 1.4.0 
```

**Comment by dirk-thomas** [comment]
Please provide more information: steps to reproduce, e.g. the content which fails to lint, the version of `xmllint` you are having installed, etc.

**Comment by creadri** [comment]
Thanks for your message. The steps to reproduce:

Create new xml file, start with file with "<" or any illegal character. It only happens creating new files.

xmlint:
Package: libxml2-utils
Priority: optional
Section: text
Installed-Size: 176
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian XML/SGML Group <debian-xml-sgml-pkgs@lists.alioth.debian.org>
Architecture: amd64
Source: libxml2
Version: 2.9.3+dfsg1-1
Depends: libc6 (>= 2.14), libxml2 (>= 2.9.0)
Filename: pool/main/libx/libxml2/libxml2-utils_2.9.3+dfsg1-1_amd64.deb
Size: 34958
MD5sum: c470bca15fadf7c4182bc75e45055f69
SHA1: e842b9b0e2a0e0a9555a32c1db8ebe2173afb3bf
SHA256: 58f9c7f32950b78911050955c1d478f02ac6cc12f5bd80c4413892ca0ba02162


xmllint: using libxml version 20903


Hope it helps.

**Comment by dirk-thomas** [comment]
Thank you for the additional information. I was able to reproduce the problem. The issue was that the error message doesn't contain a trailing newline and the source line / marker indication where the error is. I created #82 to make the regex more flexible to handle that case and actually detect that the file is not well formed. That prevent the file from being parsed which lead to the exception.

**Comment by dirk-thomas** [comment]
The new version 1.4.3 contains the fix.
