### ISSUE TITLE
xml linter instal on w10

### ISSUE THREAD

**Issue by barremans** [AtomLinter/linter-xmllint#88]
Error running xmllint Error: Failed to spawn command `xmllint`. Make sure `xmllint` is installed and on your PATH
    at C:\Users\bmcba\.atom\packages\linter-xmllint\node_modules\atom-linter\lib\helpers.js:130:24
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by dirk-thomas** [comment]
Please add more information to the ticket. The error message you posted is pretty self describing. This is not a bug but you don't have `xmllint` installed on the `PATH`.

**Comment by dirk-thomas** [comment]
Closing for now due to no response.
