### ISSUE TITLE
linter-xmllint doesn't work

### ISSUE THREAD

**Issue by noeliacast** [AtomLinter/linter-xmllint#89]
I tried to use Atom to verify my xml file and check errors, but the package linter-xmllint seems to do nothing. Nor linter errors or warnings pop up on my file even though I make them to see if it's works.

**Comment by dirk-thomas** [comment]
The ticket doesn't contain enough information to offer you any help. What platform are you on? Have you installed the `xmllint` executable and confirmed that it works from the command line? Does it output the linter messages you expect when you run it on the command line for your file?

**Comment by dirk-thomas** [comment]
Closing due to no response.
