### ISSUE TITLE
The linter binary 'xmllint' cannot be found.

### ISSUE THREAD

**Issue by Yajo** [AtomLinter/linter-xmllint#9]
This package gives this error, but if I open a terminal:

    $ which xmllint
    /usr/bin/xmllint

**Comment by Yajo** [comment]
Versions:

- atom-0.196.0-0.1.fc21.x86_64
- linter-xmllint 0.0.5

**Comment by steelbrain** [comment]
I am not able to reproduce this behaviour on Ubuntu 15.04.

**Comment by centzon400** [comment]
Exactly the same situation on:
* OS X 10.10.3
* Atom 1.0.0
* linter-xmllint 0.0.6
* CoffeeScript version 1.9.3

**Comment by Arcanemagus** [comment]
A complete re-write has been merged in, if you are still having issues please file a new issue.
