### ISSUE TITLE
Uncaught Error: Unexpected close tag Line: 3 Column: 18 Char: >

### ISSUE THREAD

**Issue by TheHaricover** [AtomLinter/linter-xmllint#93]
1. Open an XML file
2. Write ```<name>1</nme>``` in it.

I have a lot of issues, so it may be my fault. I don't have the time to seek for the offending, so I'm letting this issue here and I'll just deactivate the package for now

**Atom**: 1.24.1 x64
**Electron**: 1.6.16
**OS**: Windows 10 Familial (Version 10.0.16299 Number 16299)
**Thrown From**: [linter-xmllint](https://github.com/AtomLinter/linter-xmllint) package 1.4.3

### Stack Trace

Uncaught Error: Unexpected close tag
Line: 3
Column: 18
Char: >

```
At events.js:160

Error: Unexpected close tag
Line: 3
Column: 18
Char: >
    at error (/packages/linter-xmllint/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/packages/linter-xmllint/node_modules/sax/lib/sax.js:677:7)
    at closeTag (/packages/linter-xmllint/node_modules/sax/lib/sax.js:871:9)
    at SAXParser.write (/packages/linter-xmllint/node_modules/sax/lib/sax.js:1436:13)
    at SAXStream.write (/packages/linter-xmllint/node_modules/sax/lib/sax.js:239:18)
    at ReadableString.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at ReadableString.emit (events.js:188:7)
    at ReadableString.Readable.read (_stream_readable.js:381:10)
    at flow (_stream_readable.js:761:34)
    at resume_ (_stream_readable.js:743:3)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -5:08.9.0 intentions:highlight (input.hidden-input)
     -5:08.8.0 core:paste (input.hidden-input)
     -5:08.5.0 intentions:highlight (input.hidden-input)
     -5:08.4.0 core:save (input.hidden-input)
     -4:10.5.0 core:backspace (input.hidden-input)
     -4:10.1.0 intentions:highlight (input.hidden-input)
     -4:10 core:save (input.hidden-input)
     -4:08.3.0 intentions:highlight (input.hidden-input)
  2x -4:08.1.0 core:copy (input.hidden-input)
  2x -4:07.0 editor:newline (input.hidden-input)
     -4:06.7.0 intentions:highlight (input.hidden-input)
     -4:06.6.0 core:paste (input.hidden-input)
     -4:04.1.0 core:delete (input.hidden-input)
     -4:03.2.0 intentions:highlight (input.hidden-input)
     -4:03.1.0 core:save (input.hidden-input)
  6x -1:48.4.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-clock 0.1.16 
atom-ide-ui 0.9.3 
atom-python-run 0.9.6 
autocomplete-python 1.10.5 
autocomplete-xml 0.9.4 
autumn-highlighter-syntax 1.13.0 
busy-signal 1.4.3 
highlight-selected 0.13.1 
Hydrogen 2.3.0 
ide-csharp 0.6.2 
intentions 1.1.5 
kite 0.72.0 
linter 2.2.0 
linter-ui-default 1.7.1 
linter-xmllint 1.4.3 
package-switch 0.5.0 
python-tools 0.6.9 
sync-settings 0.8.5 
webbox-color 0.5.9 
xml-formatter 0.11.0 
```

**Comment by dirk-thomas** [comment]
Can you please post the version of the `sax` package you are experiencing the problem with. You will find the "version" key in the file `<atom>/packages/linter-xmllint/node_modules/sax/package.json`.

**Comment by dirk-thomas** [comment]
@TheHaricover While I am unable to reproduce the problem your case might trigger an `onerror` call from the sax parser which this plugin currently doesn't handle. I have create the branch [add_onerror_handler](https://github.com/AtomLinter/linter-xmllint/tree/add_onerror_handler) which adds a handler for that. Since I don't know how to trigger that event I can't check if this addresses your case (I can't even say if my added code works). If you could try the code from that branch locally (in development mode) and report back what happens that would be great. You should see a "normal" linter error in the case that threw before and also so a warning message starting with "onerror" on the developer console.

**Comment by TheHaricover** [comment]
Here's the version of "sax" : 1.2.4
I'll see what I can do for the test of the developer branch

**Comment by dirk-thomas** [comment]
@TheHaricover did you have a chance to try the patch?

**Comment by TheHaricover** [comment]
Not at all, sorry. I'll try when I can !

**Comment by dirk-thomas** [comment]
@TheHaricover Friendly ping.

**Comment by TheHaricover** [comment]
I'm sorry. I'm in the middle of exams. The patch installed itself on Atom right ? If so, I have an XML exam friday. And I'll probably try to use your linter, so we'll see. If I don't answer, continue to ping me 😆

**Comment by TheHaricover** [comment]
So, I think I have to apply the patch you're talking about. But I don't really know how to do the test. I'll be busy for some time, but if I find the time I'll try to figure it out.
Today I tested again your package and got another error. It was because I put an attribute without value (so without '=' or '""')
